Bump GL JS to v2.0.5
maplibre/maplibre-gl-js-docs pull request #112
Opened 2022-01-24 15:41 UTC by wipfli

2022-01-24 15:44 UTC, HarelM approved these changes

2022-01-26 20:42 UTC, HarelM requested changes

2022-01-26 20:42 UTC, HarelM commented on package.json
> +    "node": ">=16"
Remove this

2022-01-26 20:42 UTC, HarelM commented on package.json
> +    "install-gl-js-deps": "cd maplibre-gl-js/ && npm ci",
Update lock file to be node 16 too

2022-01-26 20:56 UTC, wipfli commented on package.json
> +    "install-gl-js-deps": "cd maplibre-gl-js/ && npm ci",
Thanks for the hint.

2022-01-27 05:12 UTC, HarelM approved these changes

2022-01-27 05:12 UTC, merged